-- Routine TODOs generated by /mb:todos-routine on 2026-06-11 (all due on first run).
-- Idempotent: INSERT OR IGNORE on the date-stamped id; source carries the routine id.

INSERT OR IGNORE INTO todos (id, title, brain, status, priority, body, source, created_at) VALUES
('rt-ads-audit-20260611',
 'Run /ads-google + /ads-budget for nitokyo.shop; log findings as next actions',
 'claude-ads', 'open', 'high',
 'Recurring (every 2w). Re-audit the live Google Ads account 347-392-5494. Next: check whether the Wholesale Search budget was raised and the Contact conversion goal fixed; re-pull search terms + wasted spend.',
 'routine:ads-audit', '2026-06-11'),

('rt-seo-refresh-20260611',
 'marketing-brain: re-run keyword/competitor research, decide next action for nitokyo.shop',
 'marketing-brain', 'open', 'normal',
 'Recurring (every 1m). Re-run DataForSEO competitor + keyword pull, diff against this month, refresh the BEAST plan priorities. Next: confirm whether the duplicate-title P0 fix shipped and the site started ranking.',
 'routine:seo-refresh', '2026-06-11'),

('rt-site-recrawl-20260611',
 'website-brain: re-crawl nitokyo.shop and diff against the last capture',
 'website-brain', 'open', 'low',
 'Recurring (every 3m). Re-crawl nitokyo.shop and diff pages/brand vs the 2026-06-11 capture. Next: confirm /personalshopper + /influencer are now in the sitemap and crawlable.',
 'routine:site-recrawl', '2026-06-11'),

('rt-client-report-20260611',
 'Refresh the fused client intelligence report for nitokyo.shop (/mb:report)',
 'client-intelligence-report', 'open', 'normal',
 'Recurring (every 3m). Regenerate the fused SEO + paid intelligence report and PDF with the latest numbers. Next: compare paid CPA/IS and organic rankings vs the 2026-06-11 baseline.',
 'routine:client-report', '2026-06-11'),

('rt-backlog-review-20260611',
 'Triage the TODO backlog (/mb:todos-review)',
 'manual', 'open', 'normal',
 'Recurring (every 2w). Dedupe, reprioritize, mark stale/blocked so the board stays trustworthy.',
 'routine:backlog-review', '2026-06-11');
