-- Add a `kind` column to classify each TODO: 'routine' (recurring) | 'one_time' (ad-hoc).
ALTER TABLE todos ADD COLUMN kind TEXT NOT NULL DEFAULT 'one_time';

-- Backfill: anything generated by the routine engine is a routine; the rest are one-time.
UPDATE todos SET kind = 'routine' WHERE source LIKE 'routine:%';
